version: '3'

services:
  backend:
    build:
      context: ./brainly-server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./brainly-server:/Brainly
      - /Brainly/node_modules
    environment:
      - NODE_ENV=development
      - JWT_SECRET_KEY=iamarnabssecrectkeybaby
      - MONGODB_URI=mongodb+srv://hparnab0:u2FHHUheetWxdJ7N@brainly.a9e87.mongodb.net/?retryWrites=true&w=majority&appName=Brainly
      - CORS_ORIGIN=http://localhost:4173,http://localhost:5173

  frontend:
    build:
      context: ./brainly-client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./brainly-client:/Brainly
      - /Brainly/node_modules
    environment:
      - VITE_API_BASE=http://localhost:3000
