version: '3'

services:
  backend:
    build:
      context: ./brainly-server
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - ./brainly-server:/Brainly
      - /Brainly/node_modules
    environment:
      - NODE_ENV=
      - JWT_SECRET_KEY=
      - MONGODB_URI=
      - CORS_ORIGIN=

  frontend:
    build:
      context: ./brainly-client
      dockerfile: Dockerfile.prod
    ports:
      - "4173:4173"
    volumes:
      - ./brainly-client:/Brainly
      - /Brainly/node_modules
    environment:
      - VITE_API_BASE=
