FROM node:22-alpine

WORKDIR /Brainly

COPY package*.json ./

RUN npm install

COPY . .

# Build the Vite app
RUN npm run build

# Set the port Vite will serve on (default for preview is 4173)
ENV PORT=4173
EXPOSE 4173

# Serve the built app
CMD [ "npm", "run", "preview" ]
