name: Deploy to Azure VM

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.AZURE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} << 'EOF'
            cd /home/${{ secrets.AZURE_USER }}/Brainly/brainly-server
            git pull origin main
            sudo apt update
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            source ~/.bashrc
            nvm install --lts
            sudo npm install -g pm2
            npm install
            pm2 restart all || pm2 start npm --name "myapp" -- run start
          EOF
